trigger:
- main

pool:
  name: Default

steps:
- checkout: self  # ✅ Fix: Checkout code from GitHub

- task: Maven@3  # Build Spring Boot app
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true

- task: CopyFiles@2  # Copy JAR file to staging directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1  # Publish JAR as a pipeline artifact
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
